#!/usr/bin/env bash
# Configure your Nginx server so that 
# /redirect_me is redirecting to another page

# update the local package and install nginx
apt-get update -y
apt-get install nginx -y

# firewall allow access to nginx service
ufw allow 'Nginx HTTP'

ufw status #VERBOSE

service nginx --full-restart

echo "Hello World!" > /var/www/html/index.nginx-debian.html

newString="server_name marviel.com"
sed -i "s/server_name _/$newString/" /etc/nginx/sites-available/default

# for location
newLocat="location /redirect_me {\n\
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
\t}"

sed -i "/$newString/a\\\n\t$newLocat" /etc/nginx/sites-available/default

service nginx restart

