#!/usr/bin/env bash
# Configure your Nginx server so that 
# /redirect_me is redirecting to another page

echo -e "server{\n\
	server_name marviel.com\n\
	rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent\n\
}" > /redirect_me
