#!/usr/bin/env bash
# Configure your Nginx server so that 
# /redirect_me is redirecting to another page

newString="server_name marviel.com"
sed -i "s/server_name _/$newString/" /etc/nginx/sites-available/default

# for location
newLocat="location /redirect_me {\n\
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
\t}"

sed -ie "/$newString/a\\\n\t$newLocat" /etc/nginx/sites-available/default

service nginx restart

