#!/usr/bin/env bash

# Install nginx on your web-01 server
# Nginx should be listening on port 80

# update the local package and install nginx
apt-get update -y
apt-get install nginx -y

# firewall allow access to nginx service
ufw allow 'Nginx HTTP'

ufw status #VERBOSE

echo "Hello World!" > /var/www/html/index.html

# Configure Nginx so that its HTTP response contains a custom header
sed -i "0,/server_name/s//add_header X-Served-By \$hostname;\n\tserver_name/" /etc/nginx/sites-available/default

service nginx --full-restart
