#!/usr/bin/env bash
# comment here
#apt update
#apt install nginx
#sed -i s/"listen 80"/"listen *:80"/ 
sed -i -e s/"listen\ 80"/"listen\ *:80"/ /etc/nginx/sites-available/default
service nginx restart
