#!/usr/bin/env bash
# redirects port 8080/TCP to port 80/TCP
rules="\
*nat\n\
:PREROUTING ACCEPT [0:0]\n\
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\n\
COMMIT\n\
"
sed -i '10i\'"$rules" before.rules 
