#!/usr/bin/env bash
# redirects port 8080/TCP to port 80/TCP
rules="\
\t*nat\n\
\t:PREROUTING ACCEPT [0:0]\n\
\t-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\n\
\tCOMMIT\n\
"
sed -i '10i\'"$rules" before.rules 
